name: analysis

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Jupyter notebooks
  - ipykernel
  - ipywidgets
  - ipympl

  # formatting
  - autopep8
  - black
  - flake8
  - pylint

  # testing
  - pytest
  - pytest-cov

  # parallelization
  - bokeh
  - dask
  - dask-labextension
  - joblib
  - tqdm

  # documentation
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx

  # plotting
  - matplotlib
  - seaborn
  - colorcet
  - cmasher

  # data analysis
  - numpy
  - pandas
  - pyarrow
  - fastparquet
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
  - rdkit

  # MD packages
  - gromacswrapper
  - mdanalysis
  - mdanalysistests
  - panedr
  - parmed
  - plumed
  - py-plumed
